version: "3.8"

services:

  front:
    image: sermalenk/skypro-front:lesson-34
    restart: always
    ports:
      - 80:80
    depends_on:
      api:
        condition: service_started

  api:
    image: ${IMAGE_TAG}:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    env_file:
      - .env
    restart: always
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    image: ${IMAGE_TAG}:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py migrate

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${NAME}
    ports:
      - "5455:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${USER} -d ${NAME}
      interval: 3s
      timeout: 5s
      retries: 10

volumes:
  db_data:
