version: "3.8"

services:

  frontend:
    image: sermalenk/skypro-front:lesson-36
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"

  api:
    image: ${IMAGE_TAG}:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    ports:
      - "8000:8000"

  migrations:
    image: ${IMAGE_TAG}:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    command: sh -c "python3 manage.py migrate"

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: sh -c "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 3s
      timeout: 5s
      retries: 10

volumes:
  db_data:
